- README.adoc
Made the translation of the README file to Portuguese.
Removed some Capitals, as for example "Titles, Text, Links" became "títulos, texto, links".
> Translated README

- Language/Functions/Main/loop.adoc
Only translated the description  and the code comments. 
The code itself is intact.
> Translated loop() function file

- Language/Functions/Main/setup.adoc
Translated the setup() function file to Portuguese and added comments to explain the example code.
> Translated setup() function file

- Language/Structure/Further Syntax/semicolon.adoc
Updated the semicolon file for the Portuguese reference.
> Translated the Semicolon file

- Language/Functions/Digital IO/digitalRead.adoc
The tags for categories and subcategories were used.
> Traslated digitalRead()

- README.adoc
Added a missing 'não' that was making the sentence about git nonsense.
> Fixed a missing 'não' (no)

- Language/Functions/Digital IO/digitalWrite.adoc
Translated this file similarly to digitalRead().
> Translated digitalWrite() file

- Language/Functions/Bits and Bytes/lowByte.adoc
Finished translating Bits and Bytes subcategory
> Translated lowByte() function

- Language/Functions/Advanced IO/tone.adoc
Finished translating Advanced I/O
> Translated tone() function

- Language/Functions/Characters/isDigit.adoc
Example code commentary was also wrong.
> Translated isDigit()

- Language/Functions/Characters/isLowerCase.adoc
The comment in the example code was just "tests if this is a letter" when it should be "tests if this is a lower case letter".
> Translated isLowerCase() function

- README.adoc
Removed extra https:// from links
> Fixed links

- Language/Functions/Math/abs.adoc
Description said absolute value of two numbers. May need fixing in the other versions too.
> Translated abs()

- Language/Functions/Characters/isWhitespace.adoc
Hello @smellai , sorry for flooding you with PRs, I did not find a way of editing all files in just one.
A tip would be very welcome.
I totally missed this bug, and only noticed it today.
> Fixed syntax code formatting

- Language/Functions/Trigonometry/tan.adoc
Added a note on the double data type giving bounds to the result.
> Translated tan()

- Language/Functions/Math/min.adoc
> Translated min()

- Language/Functions/USB/Keyboard.adoc
I guess this fixes the broken links in this page
> Removed some capitals from the links.

- Language/Functions/USB/Keyboard.adoc
This file has not been translated yet, but it is in the list of files with broken links
> Fixed some broken links in Keyboard.adoc

- Language/Functions/Time/micros.adoc
I believe I finished translating the timing functions
> Translated micros()

- Language/Functions/Time/delay.adoc
> Fixed broken link in delay()

- Language/Variables/Data Types/unsignedInt.adoc
Added info about unsigned variables from English repository.
> Updated unsignedInt.adoc 

- Language/Functions/USB/Keyboard.adoc
- Language/Functions/USB/Mouse.adoc
Update from arduino/reference-en#418
> Correct recommendations re: use of Serial.print() to debug Keyboard/Mouse emulation

- Language/Variables/Data Types/string.adoc
mStrings -> myStrings
Fixes https://github.com/arduino/Arduino/issues/8414
> Fix incorrect variable name in string example code

- Language/Structure/Control Structure/doWhile.adoc
Fixes https://github.com/arduino/reference-en/issues/455
Fixes https://github.com/arduino/reference-pt/issues/211
> Fixing doWhile.adoc example code is incorrect

- Language/Structure/Control Structure/switchCase.adoc
Fixes https://github.com/arduino/reference-pt/issues/212
> Add missing break to switchCase example code

- Language/Variables/Variable Scope & Qualifiers/volatile.adoc
> Updated volatile page with ATOMIC macro info

- Language/Variables/Data Types/int.adoc
This fixes #214 
Updated from the English repository
> Updated int page with example

- Language/Functions/Math/map.adoc
>  Added Notes & Warnings for map() function 

- Language/Variables/Data Types/String/Functions/equalsIgnoreCase.adoc
Fixes https://github.com/arduino/reference-pt/issues/296
> Convert all files from UTF-8 BOM to UTF-8 encoding

- Language/Functions/Digital IO/digitalWrite.adoc
> Note that the Nano's A6 and A7 can not be used as digital pins

- Language/Structure/Arithmetic Operators/assignment.adoc
- Language/Structure/Control Structure/for.adoc
- Language/Structure/Control Structure/goto.adoc
- Language/Structure/Control Structure/if.adoc
- Language/Structure/Further Syntax/curlyBraces.adoc
- Language/Structure/Further Syntax/define.adoc
- Language/Variables/Data Types/array.adoc
- Language/Variables/Data Types/string.adoc
- Language/Variables/Utilities/PROGMEM.adoc
- Language/Variables/Variable Scope & Qualifiers/scope.adoc
> Fix references to "C programming language" 

- Language/Variables/Utilities/sizeof.adoc
> Move note about null terminator to a more appropriate location

- Language/Functions/Advanced IO/pulseIn.adoc
- Language/Functions/Advanced IO/pulseInLong.adoc
> Make the pulseIn/pulseInLong example actually do something

- Language/Variables/Data Types/String/Functions/toDouble.adoc
- Language/Variables/Data Types/stringObject.adoc
> Document String.toDouble()

- Language/Structure/Bitwise Operators/bitwiseAnd.adoc
- Language/Structure/Bitwise Operators/bitwiseOr.adoc
- Language/Structure/Bitwise Operators/bitwiseXor.adoc
> Note architecture and board specificity of bitwise operators example code

- Language/Functions/Communication/serial.adoc
Fixes https://github.com/arduino/reference-pt/issues/240
> Fix capitalization of if in if(Serial) link

- Language/Variables/Data Types/size_t.adoc
> Documented size_t

- Language/Variables/Data Types/size_t.adoc
> Fix broken links in size_t reference

- Language/Functions/Math/pow.adoc
Fixes #248.
Update from the English repository
> Add basic example for pow()

- Language/Functions/Communication/Stream/streamAvailable.adoc
- Language/Functions/Communication/Stream/streamFind.adoc
- Language/Functions/Communication/Stream/streamFindUntil.adoc
- Language/Functions/Communication/Stream/streamFlush.adoc
- Language/Functions/Communication/Stream/streamGetTimeout.adoc
- Language/Functions/Communication/Stream/streamParseFloat.adoc
- Language/Functions/Communication/Stream/streamParseInt.adoc
- Language/Functions/Communication/Stream/streamPeek.adoc
- Language/Functions/Communication/Stream/streamRead.adoc
- Language/Functions/Communication/Stream/streamReadBytes.adoc
- Language/Functions/Communication/Stream/streamReadBytesUntil.adoc
- Language/Functions/Communication/Stream/streamReadString.adoc
- Language/Functions/Communication/Stream/streamReadStringUntil.adoc
- Language/Functions/Communication/Stream/streamSetTimeout.adoc
> Improve wording of Stream class description

- Language/Functions/Communication/Serial/available.adoc
- Language/Functions/Communication/Serial/find.adoc
- Language/Functions/Communication/Serial/parseInt.adoc
- Language/Functions/Communication/Serial/peek.adoc
- Language/Functions/Communication/Serial/read.adoc
- Language/Functions/Communication/Serial/readBytes.adoc
- Language/Functions/Communication/Serial/readBytesUntil.adoc
- Language/Functions/Communication/Serial/readString.adoc
- Language/Functions/Communication/Serial/readStringUntil.adoc
- Language/Functions/Communication/Serial/setTimeout.adoc
> Consistently document inheritance from Stream class

- Language/Functions/Math/constrain.adoc
- Language/Functions/Math/sq.adoc
> Add warnings about doing operations inside macro parameters

- Language/Functions/Communication/Serial/begin.adoc
> Add note re: irrelevance of Serial.begin() for USB CDC ports

- Language/Structure/Compound Operators/compoundRemainder.adoc
> Document compound remainder

- Language/Functions/Characters/isAlpha.adoc
- Language/Functions/Characters/isAlphaNumeric.adoc
- Language/Functions/Characters/isAscii.adoc
- Language/Functions/Characters/isControl.adoc
- Language/Functions/Characters/isDigit.adoc
- Language/Functions/Characters/isGraph.adoc
- Language/Functions/Characters/isHexadecimalDigit.adoc
- Language/Functions/Characters/isLowerCase.adoc
- Language/Functions/Characters/isPrintable.adoc
- Language/Functions/Characters/isPunct.adoc
- Language/Functions/Characters/isSpace.adoc
- Language/Functions/Characters/isUpperCase.adoc
- Language/Functions/Characters/isWhitespace.adoc
> Don't use reserved name (this) as a variable name in the example code

- Language/Functions/External Interrupts/attachInterrupt.adoc
- Language/Functions/External Interrupts/detachInterrupt.adoc
> Correct information about attach/detach interrupt compatibility

- Language/Variables/Data Types/String/Functions/remove.adoc
> Add example code to String.remove() page

- Language/Structure/Further Syntax/include.adoc
> Use beginner-friendly code as an example for #include

- Language/Variables/Data Types/char.adoc
> Correct char documentation re: size and signedness

- Language/Functions/Time/millis.adoc
> Small fixes in millis()

- Language/Functions/Time/delay.adoc
Added link to the sketch Blink Without Delay. 
Fixes #363
> Inline link to Blink Without Delay sketch

- Language/Functions/Bits and Bytes/bitWrite.adoc
Added example code of bitWrite.
Update from the English repo. Fixes #365
> Bit write example

- README.adoc
Updated the link of analogwrite(), serial(), arduino reference webpage.
> updated readme

- Language/Functions/USB/Keyboard/keyboardBegin.adoc
- Language/Functions/USB/Keyboard/keyboardModifiers.adoc
- Language/Variables/Data Types/String/Functions/reserve.adoc
Fixes https://github.com/arduino/reference-pt/issues/390
> Fix unterminated asciidoc blocks

- Language/Functions/Time/millis.adoc
começou em substituição a começo
> Correção de erro de digitação

- Language/Functions/Advanced IO/noTone.adoc
- Language/Functions/Advanced IO/pulseIn.adoc
- Language/Functions/Advanced IO/pulseInLong.adoc
- Language/Functions/Advanced IO/tone.adoc
- Language/Functions/Analog IO/analogWrite.adoc
- Language/Functions/Digital IO/digitalRead.adoc
- Language/Functions/Digital IO/digitalWrite.adoc
- Language/Functions/Digital IO/pinMode.adoc
- Language/Functions/External Interrupts/attachInterrupt.adoc
- Language/Functions/External Interrupts/detachInterrupt.adoc
Fixes #397 
Update from the English repository
> Emphasize that IO functions take Arduino pin numbers

- Language/Functions/Advanced IO/pulseInLong.adoc
changing a paragraph that was not translated into Portuguese
> Update pulseInLong.adoc (Translation)
