arduino/reference-pt

- Language/Functions/Characters/isAlpha.adoc
There seems to be something wrong with the example code tough.
It seems to be testing is a variable is alpha, but says to the user that is is alphanumeric.
May need fixing.
> Translated isAlpha()

- Language/Functions/Math/max.adoc
There seems to be a typo in the variable name in the function inside the example code (judging by the comment).
May need fixing in the other versions
> Translated max()

- Language/Functions/Advanced IO/shiftOut.adoc
It seems the SPI library was in the language reference before, but it was moved out. Updated the link to https://www.arduino.cc/en/Reference/SPI
> Fixed some broken links in shiftOut()

- Language/Functions/External Interrupts/attachInterrupt.adoc
Fixes https://github.com/arduino/reference-pt/issues/209
> fenced functions mentioned in text with backticks to render them as <code>

- Language/Functions/Advanced IO/noTone.adoc
- Language/Functions/Advanced IO/pulseIn.adoc
- Language/Functions/Advanced IO/pulseInLong.adoc
- Language/Functions/Advanced IO/shiftIn.adoc
- Language/Functions/Advanced IO/shiftOut.adoc
- Language/Functions/Bits and Bytes/bit.adoc
- Language/Functions/Bits and Bytes/bitClear.adoc
- Language/Functions/Bits and Bytes/bitRead.adoc
- Language/Functions/Bits and Bytes/bitSet.adoc
- Language/Functions/Bits and Bytes/bitWrite.adoc
- Language/Functions/External Interrupts/attachInterrupt.adoc
- Language/Functions/External Interrupts/detachInterrupt.adoc
- Language/Functions/Interrupts/noInterrupts.adoc
- Language/Functions/Math/abs.adoc
- Language/Functions/Math/constrain.adoc
- Language/Functions/Math/map.adoc
- Language/Functions/Math/max.adoc
- Language/Functions/Math/min.adoc
- Language/Functions/Math/sq.adoc
- Language/Functions/Math/sqrt.adoc
- Language/Functions/Random Numbers/random.adoc
- Language/Functions/Random Numbers/randomSeed.adoc
- Language/Functions/Time/delayMicroseconds.adoc
- Language/Functions/Time/micros.adoc
- Language/Structure/Sketch/loop.adoc
- Language/Structure/Sketch/setup.adoc
- Language/Variables/Data Types/word.adoc
- Language/Variables/Utilities/sizeof.adoc
- Language/Variables/Variable Scope & Qualifiers/scope.adoc
When the "See also" section is missing, the automatically generated links to the other pages within the same subsection are added to a section titled "undefined".
Fixes https://github.com/arduino/reference-pt/issues/229
> Add missing "See also" sections

- Language/Structure/Control Structure/goto.adoc
A label that is not followed by a statement results in a somewhat confusing compilation error. It is hoped that a simple comment in the example code will steer people in the right direction without requiring an increase in the complexity of the description or notes for `goto`.
Fixes https://github.com/arduino/reference-pt/issues/237
> Add comment to goto example code to indicate that a label must be followed by a statement

- Language/Functions/Communication/Serial/findUntil.adoc
Fixes https://github.com/arduino/reference-pt/issues/238
> Remove empty "Notes and Warnings" section from Serial.findUntil()

- Language/Functions/Communication/Serial/readBytesUntil.adoc
readByteUntil -> readBytesUntil
Fixes https://github.com/arduino/reference-pt/issues/239
> Correct function name in "See Also" link

- Language/Functions/Communication/Stream/streamReadBytesUntil.adoc
Fixes https://github.com/arduino/reference-pt/issues/245
> Fix markup of Stream.readBytesUntil() length parameter documentation

- Language/Variables/Data Types/String/Functions/c_str.adoc
- Language/Variables/Data Types/String/Functions/concat.adoc
- Language/Variables/Data Types/String/Functions/remove.adoc
- Language/Variables/Data Types/String/Functions/reserve.adoc
Some of the reference pages were missing this from the Parameters section.
Fixes https://github.com/arduino/reference-pt/issues/243
> Document String variable in Parameters section of String functions

- Language/Structure/Control Structure/if.adoc
Previously, the "entity title" of the page was "if...else", but this page makes no mention of else. There is a separate page that documents else. The page title "if (conditional) and ==, !=, <, > (comparison operators)" is also unnecessarily confusing. There are separate reference pages for the comparison operators.
Fixes https://github.com/arduino/reference-pt/issues/280
> Correct misleading/confusing titles of if reference page

- Language/Variables/Data Types/String/Functions/toDouble.adoc
Beginners are frequently confused about String vs strings so it's important to make a clear distinction between the two in the documentation.
This is an extension of https://github.com/arduino/reference-pt/pull/267, which was not able to affect the `toDouble` reference page since it didn't exist at that time.
Fixes #233
> Always use capital s when referring to String objects

- Language/Variables/Data Types/String/Functions/toDouble.adoc
The space between link: and the URL caused the "link:" to be shown as text on the page. Since all the other example links do not use the link: markup, I removed it from the incorrectly formatted links.
Fixes https://github.com/arduino/reference-pt/issues/241
> Fix formatting of example link on toDouble page

- Language/Variables/Data Types/String/Functions/toDouble.adoc
This is an extension of https://github.com/arduino/reference-pt/pull/306, which was not able to affect the `toDouble` reference page since it didn't exist at that time.
Fixes #296
> Convert toDouble page from UTF-8 BOM to UTF-8 encoding

- Language/Functions/Communication/Serial/getTimeout.adoc
- Language/Functions/Communication/Stream/streamGetTimeout.adoc
> Document Stream.getTimeout()

- Language/Functions/Communication/Serial/serialEvent.adoc
> Add Yun to the list of the boards serialEvent() doesn't work for

- Language/Functions/Digital IO/digitalRead.adoc
> Add note that the Nano, et al. A6 and A7 can not be used as digital pins

- Language/Structure/Further Syntax/curlyBraces.adoc
> Added missing comments to statement(s) section in curlyBraces

- Language/Variables/Utilities/sizeof.adoc
> Improve sizeof example code

- Language/Variables/Data Types/bool.adoc
- Language/Variables/Data Types/byte.adoc
- Language/Variables/Data Types/char.adoc
- Language/Variables/Data Types/double.adoc
- Language/Variables/Data Types/float.adoc
- Language/Variables/Data Types/int.adoc
- Language/Variables/Data Types/long.adoc
- Language/Variables/Data Types/short.adoc
- Language/Variables/Data Types/size_t.adoc
- Language/Variables/Data Types/unsignedChar.adoc
- Language/Variables/Data Types/unsignedInt.adoc
- Language/Variables/Data Types/unsignedLong.adoc
- Language/Variables/Data Types/word.adoc
> Document syntax for data types where missing

- Language/Variables/Data Types/word.adoc
> Correct documentation of word data type's size

- AsciiDoc_sample/AsciiDoc_Dictionary/AsciiDoc_Template-Dictionary.adoc
- Language/Structure/Control Structure/break.adoc
Fix formatting issues which were not covered by the auto format.
Fix formatting issues in AsciiDoc_Template-Dictionary.adoc, which I accidentally skipped during the auto format.
Fixes https://github.com/arduino/reference-pt/issues/353
> Fix formatting of example code

- Language/Structure/Pointer Access Operators/reference.adoc
- Language/Variables/Data Types/String/Operators/lessThan.adoc
- Language/Variables/Data Types/int.adoc
Following the standard established by the reference sample pages.
Fixes https://github.com/arduino/reference-pt/issues/354
> Use a single space after period

- Language/Functions/Advanced IO/tone.adoc
- Language/Functions/Communication/Serial/serialEvent.adoc
I'm following the example of the Tutorials page in how to format the link text for the tutorial links.
Fixes https://github.com/arduino/reference-pt/issues/369
> Standardize link text

- Language/Functions/Communication/Stream/streamParseFloat.adoc
Fixes https://github.com/arduino/reference-pt/issues/372
> Fixed broken link and spelling in streamParseFloat.adoc.

- Language/Functions/Communication/Serial/serialEvent.adoc
- Language/Structure/Control Structure/while.adoc
These two tutorial links are no different from the many other example links on the other reference pages, yet they have the word "Tutorial" added, contrary to the standard established in the reference samples. There are some other instances of the use of "Tutorial" in the link text, but in those cases the link does lead to more of a general tutorial than a standard tutorial for an example sketch, so I have left those as is.
Fixes https://github.com/arduino/reference-pt/issues/383
> Be consistent with the use of "Tutorial" in link text

- Language/Functions/Communication/Serial/println.adoc
- Language/Functions/USB/Mouse/mouseRelease.adoc
- Language/Variables/Data Types/String/Functions/substring.adoc
- Language/Variables/Data Types/unsignedInt.adoc
These issues were reported by the site build tool:
```
ERROR 2019/06/07 22:34:31 asciidoctor: WARNING: Language/Functions/USB/Mouse/mouseRelease.adoc: line 92: unterminated open block
ERROR 2019/06/07 22:34:54 asciidoctor: WARNING: Language/Functions/Communication/Serial/println.adoc: line 75: unterminated open block
ERROR 2019/06/07 22:37:51 asciidoctor: WARNING: Language/Variables/Data Types/String/Functions/substring.adoc: line 19: unterminated listing block
ERROR 2019/06/07 22:38:08 asciidoctor: WARNING: Language/Variables/Data Types/unsignedInt.adoc: line 24: section title out of sequence: expected level 1, got level 2
```
> Fix asciidoc markup errors

- Language/Functions/Analog IO/analogRead.adoc
- Language/Functions/Analog IO/analogReference.adoc
- Language/Functions/Digital IO/digitalRead.adoc
- Language/Functions/Digital IO/digitalWrite.adoc
- Language/Functions/Digital IO/pinMode.adoc
> Use consistent link text for digital/analog pins tutorial links

- Language/Functions/Analog IO/analogReference.adoc
> Document analogReference() parameter values for megaAVR
